### ISSUE TITLE
突然失效

### ISSUE THREAD

**Issue by lvyanfeng07** [lunadream/XWall#18]
上周开始X-Wall突然就失效了- -弄了半天也没好,不知道是不是因为封了google端口所以goagent也不能用了啊?跪求解决....非常...需要...翻墙...

**Comment by Aivier** [comment]
Goagent可能会在后续更新，目前的新版并不包含Goagent组件，已安装带GoAgent版本的用户暂时无法自动更新，如果手动升级将会失去Goagent功能

**Comment by Aivier** [comment]
Hello，新版XWall已经更新，包含了最新的GoAgent客户端，如需升级GAE服务器端脚本请使用GoAgent携带的程序手动上传然后在XWall的设置页面中设置APPID
